###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.2"

volumes:
  mysql:
    driver: local

services:

    redis:
      image: redis:alpine
      container_name: g-esport-redis

    db:
      image: mariadb
      container_name: g-esport-mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=g-esport
      ports:
        - "3306:3306"
      volumes:
        - ~/.data/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    webserver:
      image: nginx:alpine
      container_name: g-esport-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: g-esport-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: g-esport-phpmyadmin
      environment:
        - PMA_HOST=db
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - 8080:8080

